spring:
  application:
  name: flyghtt-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:s2fohpM6HkgeK3kr327ZSU7PL61gt6Yo}
    name: ${DB_NAME:flyghtt_db_pzao}
    hikari:
      schema: ${DB_SCHEMA:flyghtt_db}
    url: jdbc:postgresql://${DB_HOST:dpg-cromko9u0jms73cbppd0-a.oregon-postgres.render.com}:${DB_PORT:5432}/${spring.datasource.name}?currentSchema=${spring.datasource.hikari.schema},public

  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true

security:
  jwt:
    secret-key: ${JWT_SECRET}
    expiration-time: ${JWT_EXPIRATION}

springdoc:
  api-docs:
    enabled: true

server:
  servlet:
    context-path: /api/v1
